package com.rohit.ThreadSafeChat.Common.model;

public enum MessageType {
    SEND_TEXT_REQUEST, SEND_TEXT_RESPONSE, USER_LOGIN_REQUEST, LOGIN_RESPONSE, RECEIVE_TEXT, USER_LOGOFF_REQUEST,
    LOGOFF_RESPONSE;
}
